# -*- coding: utf-8 -*-
"""NumericPreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_-qcdbIdGPjgMJF6Y5gUPbjn9_jPARt
"""

from google.colab import drive
drive.mount("/content/drive")

import numpy as np
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_Results_Main/original.csv")

df.head(5)

print(df.shape)
df.describe()

# Check for null age
df.isnull().sum()

# Drop null age
df = df.dropna(subset = ['age'])

# Check for negative age
df[df['age'] < 0]

# Drop negative age
negativeAge = df[df['age'] < 0].index
df.drop(negativeAge, axis=0, inplace=True)

# Check again for negative age
df[df['age'] < 0]

# Drop clientid and shuffle rows
df = df.drop(columns=['clientid'])
df = df.sample(frac=1).reset_index(drop=True)
df

df.to_csv("/content/drive/MyDrive/ML_Results/preprocessed.csv", index=False, index_label=True)