# -*- coding: utf-8 -*-
"""ANN_Img.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSoeyjDIqPOyzaqLOtLwuznrb9y6YMK7
"""

from google.colab import drive
drive.mount("/content/drive")

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import pickle

pickle_in = open('/content/drive/MyDrive/ML_Results/Preprocessing/X_ANN_Img_Pre.pickle','rb')
X = np.array(pickle.load(pickle_in))
pickle_in.close()

pickle_in = open('/content/drive/MyDrive/ML_Results/Preprocessing/Y_ANN_Img_Pre.pickle','rb')
Y = np.array(pickle.load(pickle_in))
pickle_in.close()

print("Number of images in dataset: " ,len(X))

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4)

image_size = X_train.shape[1]
input_size = image_size
print("Number of features in image: ", input_size)

X_train=np.reshape(X_train, [-1,input_size])
X_train=X_train.astype('float32')/255

X_test=np.reshape(X_test, [-1,input_size])
X_test=X_test.astype('float32')/255

checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath="/content/drive/MyDrive/ML_Results_Main/ANN_Img_weights.h5", verbose=1, save_best_only=True)

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 512,activation='relu'))
ann.add(tf.keras.layers.Dense(units = 256,activation='relu'))
ann.add(tf.keras.layers.Dense(units = 128,activation='relu'))
ann.add(tf.keras.layers.Dense(units = 1,activation='linear'))
ann.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

history = ann.fit(X_train, y_train, epochs = 20, batch_size=80, validation_split = 0.2, callbacks=[checkpoint])

loss, acc = ann.evaluate(X_test,y_test)

print()
print("Loss: ", loss)
print("Accuracy: ", acc)

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_curve, auc, roc_auc_score

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

print("Classification report for classifier %s:\n%s\n" % (
    ann, classification_report(y_test, y_pred)))

################# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix")
print(cm)

################ Accuracy
print()
print("Model accuracy: ", accuracy_score(y_test, y_pred))

################### Loss Curve
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Training loss', 'Validation loss'], loc='center right')
plt.show()

################## ROC Curve
y_pred = y_pred.ravel()
fpr, tpr, _ = roc_curve(y_test,  y_pred)
plt.plot(fpr,tpr)
auc = roc_auc_score(y_test, y_pred)
plt.plot(fpr,tpr,label="AUC="+str(auc))
plt.title('ROC Curve')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.legend(loc=4)
plt.show()

##################### To predict from validation images
import tensorflow as tf
import cv2
import matplotlib.image as mpimg

model = tf.keras.models.load_model("/content/drive/MyDrive/ML_Results_Main/ANN_Img_80.2")

figure, axis = plt.subplots(1, 2)

def ANN_img_preprocessing(img):
  image = cv2.imread(img)
  gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  resized_gray = cv2.resize(gray, (120,120))
  edged_gray = cv2.Canny(resized_gray, 100, 200)

  axis[1].imshow(edged_gray)
  axis[1].set_title("Pre-processed image")
  
  edged_gray = np.array(edged_gray).flatten()
  return edged_gray

PATH = "/content/drive/MyDrive/C-NMC_Leukemia/validation_data/C-NMC_test_prelim_phase_data/202.bmp"


img = mpimg.imread(PATH)
axis[0].imshow(img)
axis[0].set_title("Original image")

fileimg = ANN_img_preprocessing(PATH)

fileimg = np.reshape(fileimg, [-1,input_size])
fileimg = fileimg.astype('float32')/255

y_pred = model.predict(fileimg)
y_pred = (y_pred > 0.5)

print("Prediction result: ", y_pred)

ann.save("/content/drive/MyDrive/ML_Results_Main/ANN_Img_80.2")