# -*- coding: utf-8 -*-
"""Before_SVM_Numeric.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139sqI00BFHFWa-EU6GUyCr36gSgfAD4p
"""

from google.colab import drive
drive.mount("/content/drive")

import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


df = pd.read_csv("/content/drive/MyDrive/ML_Results/preprocessed.csv")

X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

svm = SVC(C = 0.01, kernel = 'linear' , gamma = 1)
svm.fit(X_train, y_train)

accuracy = svm.score(X_test, y_test)

print("Accuracy: ", accuracy*100,'%')

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, roc_curve, auc, roc_auc_score

y_pred = svm.predict(X_test)

print("Classification report for classifier %s:\n%s\n" % (
    svm, classification_report(y_test, y_pred)))

################# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix")
print(cm)

################ Accuracy
print()
print("Model accuracy: ", accuracy_score(y_test, y_pred))

from mlxtend.plotting import plot_learning_curves
plot_learning_curves(X_train, y_train, X_test, y_test, svm)

################## ROC Curve
y_pred = y_pred.ravel()
fpr, tpr, _ = roc_curve(y_test,  y_pred)
plt.plot(fpr,tpr)
auc = roc_auc_score(y_test, y_pred)
plt.plot(fpr,tpr,label="AUC="+str(auc))
plt.title('ROC Curve')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.legend(loc=4)
plt.show()

import pickle
fileName = "/content/drive/MyDrive/ML_Results_Main/SVM_Numeric_98.model"
pickle.dump(svm, open(fileName, 'wb'))